### PR TITLE
Add 3 things

### PR DESCRIPTION
**Pull request by a11ce**
I have three projects that I think would fit well on this site. If you don't want multiple entries from the same person then pick whichever you prefer.

### CODE REVIEW

**Comment by dguo** [comment]
Hey, thanks for the suggestions, but I'm going to decline adding them. I'm going more for entertaining rather than annoying, which seems to be the goal of at least two of these.

**Comment by dguo** [comment]
Also, I know [dessert-ish](https://github.com/a11ce/dessert-ish) is intentionally horrible, but [adding a cryptominer](https://github.com/a11ce/dessert-ish/blob/master/toppings.html#L5) might be taking it a step too far.

**Comment by a11ce** [comment]
Yeah pretty much, fair enough. The cryptominer doesn't actually get me anything, it's just to use up the CPU.

**Comment by dguo** [comment]
For what it's worth, you definitely succeeded in your goal. The new window loop got me.

**Pull request closed without merging**
